contentitemexportablefields:
  contentitemfields: {}
description: |
  Playbook to demonstrate the features of XSOAR-Web-Server. It sends an html email to a set of users up to 2 times. The email can contain multiple html links, that the users can click and the response will be available in the context
id: xsoar-email-data-collection
inputs:
- description: "The emails to send the content to"
  key: useremails
  playbookInputQuery:
  required: false
  value:
    simple: Put the emails here
name: xsoar-email-data-collection
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c5cb449-cde3-4ee1-8a81-0dd24e63ebb2
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 1c5cb449-cde3-4ee1-8a81-0dd24e63ebb2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 530,
          "y": -140
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      emailsendcounter:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 248ef8ca-113b-42b5-8bb7-81c7d87480da
      iscommand: true
      name: Initializing Email Send Counter
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 248ef8ca-113b-42b5-8bb7-81c7d87480da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 125
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      emailaddresses:
        simple: ${inputs.useremails}
      htmltemplate:
        simple: ${htmltemplate}
      userstring:
        simple: postactionjob
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: setup a form submission job that can take multiple values from multiple users
      id: 6c45749a-f10f-4891-880d-b85bb7d1a3f5
      iscommand: true
      name: Setup WS Actions
      script: '|||xsoar-ws-setup-form-submission'
      type: regular
      version: -1
    taskid: 6c45749a-f10f-4891-880d-b85bb7d1a3f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 460
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 102fb6e8-b681-4cb6-8881-77b2b728f98d
      iscommand: false
      name: End
      type: title
      version: -1
      description: ''
    taskid: 102fb6e8-b681-4cb6-8881-77b2b728f98d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 530,
          "y": 1090
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: htmltemplate=
      listName:
        simple: XSOAR-WS-FormSubmission
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: 7541d261-5bb4-434f-8fc9-01397aa2823b
      iscommand: true
      name: Reading HTML template to context
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: 7541d261-5bb4-434f-8fc9-01397aa2823b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1000,
          "y": 110
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: completed
                root: WS-ActionStatus
          operator: isTrue
        - left:
            iscontext: true
            value:
              simple: incident.emailsendcounter
          operator: greaterThanOrEqual
          right:
            value:
              simple: "2"
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      EmailSubject:
        simple: test email
      FileAttachments:
        simple: ${InfoFile.EntryID}
      Jobuuid:
        simple: ${WS-ActionDetails.job_uuid}
      PollingTimebetweenRuns:
        simple: "30"
      PollingTimeout:
        simple: "180"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook tracks the user responses and  resends the emails to recipients who have not responded
      id: ef1947cf-7ae7-442a-87c0-6023c6bdb18f
      iscommand: false
      name: xsoar-data-collection-response-tracking
      playbookId: xsoar-data-collection-response-tracking
      type: playbook
      version: -1
    taskid: ef1947cf-7ae7-442a-87c0-6023c6bdb18f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 530,
          "y": 710
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      timerField:
        simple: EmailUserSLA
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.stop.timer
      id: ae779448-1c5f-4f10-8b58-176137118fdd
      iscommand: true
      name: Stopping SLA timer
      script: Builtin|||stopTimer
      type: regular
      version: -1
    taskid: ae779448-1c5f-4f10-8b58-176137118fdd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 910
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1295,
        "width": 850,
        "x": 530,
        "y": -140
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.5.0
