contentitemexportablefields:
  contentitemfields: {}
description: |
  Playbook to demonstrate the features of XSOAR-Web-Server. It sends an html email to a set of users up to 2 times. The email can contain multiple html links, that the users can click and the response will be available in the context. This playbook sets up the webserver to handle http get requests
id: xsoar-email-acknowledgement
inputs:
- description: The emails to send the data collection links to.
  key: useremails
  playbookInputQuery:
  required: false
  value:
    simple: configure the emails
name: xsoar-email-acknowledgement
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c5cb449-cde3-4ee1-8a81-0dd24e63ebb2
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 1c5cb449-cde3-4ee1-8a81-0dd24e63ebb2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 530,
          "y": -140
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      emailsendcounter:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 248ef8ca-113b-42b5-8bb7-81c7d87480da
      iscommand: true
      name: Initializing Email Send Counter
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 248ef8ca-113b-42b5-8bb7-81c7d87480da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 125
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      actions:
        simple: happy,angry
      emailaddresses:
        simple: ${inputs.useremails}
      htmltemplate:
        simple: ${htmltemplate}
      userstring:
        simple: simplegetrequestxsoarfeedback
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: setup the web server to handle URL clicks for each action specified from single or multiple recipients
      id: ef595667-d862-4246-8bde-0459e2ff76fd
      iscommand: true
      name: Setup WS Actions
      script: '|||xsoar-ws-setup-simple-action'
      type: regular
      version: -1
    taskid: ef595667-d862-4246-8bde-0459e2ff76fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 460
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 102fb6e8-b681-4cb6-8881-77b2b728f98d
      iscommand: false
      name: End
      type: title
      version: -1
      description: ''
    taskid: 102fb6e8-b681-4cb6-8881-77b2b728f98d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 530,
          "y": 1090
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: htmltemplate=
      listName:
        simple: AcknowledgementEmailHTML
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: e6d5d156-a20d-45f0-8aae-369da54279b6
      iscommand: true
      name: Reading HTML template to context
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: e6d5d156-a20d-45f0-8aae-369da54279b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1000,
          "y": 110
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: completed
                root: WS-ActionStatus
          operator: isTrue
          right:
            value: {}
        - left:
            iscontext: true
            value:
              simple: incident.emailsendcounter
          operator: greaterThanOrEqual
          right:
            value:
              simple: "2"
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      EmailSubject:
        simple: Do you like XSOAR ?
      FileAttachments:
        simple: ${InfoFile.EntryID}
      Jobuuid:
        simple: ${WS-ActionDetails.job_uuid}
      PollingTimebetweenRuns:
        simple: "30"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook tracks the user responses and  resends the emails to recipients who have not responded
      id: 79833017-77f4-4cd0-80a6-823b06e76c23
      iscommand: false
      name: xsoar-data-collection-response-tracking
      playbookId: xsoar-data-collection-response-tracking
      type: playbook
      version: -1
    taskid: 79833017-77f4-4cd0-80a6-823b06e76c23
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 530,
          "y": 710
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      timerField:
        simple: EmailUserSLA
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.stop.timer
      id: ae779448-1c5f-4f10-8b58-176137118fdd
      iscommand: true
      name: Stopping SLA timer
      script: Builtin|||stopTimer
      type: regular
      version: -1
    taskid: ae779448-1c5f-4f10-8b58-176137118fdd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 910
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1295,
        "width": 850,
        "x": 530,
        "y": -140
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.5.0
